plugins:
    vcloud:
        executor: central_deployment_agent
        source: https://github.com/cloudify-cosmo/tosca-vcloud-plugin/archive/master.zip

node_types:
    cloudify.vcloud.nodes.Server:
        derived_from: cloudify.nodes.Compute
        properties:
            use_external_resource:
                default: false
            resource_id:
                default: ''
            server:
                default: {}
            management_network:
                default: ''
            vcloud_config:
                default: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: vcloud.server_plugin.server.create
                    inputs: {}
                start:
                    implementation: vcloud.server_plugin.server.start
                    inputs: {}
                stop:
                    implementation: vcloud.server_plugin.server.stop
                    inputs: {}
                delete:
                    implementation: vcloud.server_plugin.server.delete
                    inputs: {}
            cloudify.interfaces.validation:
                creation:
                    implementation: vcloud.server_plugin.server.creation_validation

    cloudify.vcloud.nodes.Network:
        derived_from: cloudify.nodes.Network
        properties:
            network:
                default: {}
            use_external_resource:
                default: false
            resource_id:
                default: ''
            vcloud_config:
                default: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: vcloud.network_plugin.network.create
                    inputs: {}
                delete:
                    implementation: vcloud.network_plugin.network.delete
                    inputs: {}
            cloudify.interfaces.validation:
                creation:
                    implementation: vcloud.network_plugin.network.creation_validation

    cloudify.vcloud.nodes.Port:
        derived_from: cloudify.nodes.Port
        properties:
            port:
                default: {}
            vcloud_config:
                default: {}
        interfaces:
            cloudify.interfaces.validation:
                creation:
                    implementation: vcloud.network_plugin.port.creation_validation

    cloudify.vcloud.nodes.FloatingIP:
        derived_from: cloudify.nodes.VirtualIP
        properties:
            floatingip:
                default: {}
            vcloud_config:
                default: {}
        interfaces:
            cloudify.interfaces.validation:
                creation:
                    implementation: vcloud.network_plugin.floatingip.creation_validation

    cloudify.vcloud.nodes.PublicNAT:
        derived_from: cloudify.nodes.VirtualIP
        properties:
            use_external_resource:
                default: false
            nat:
                default: {}
            rules:
                default: []
            vcloud_config:
                default: {}
        interfaces:
            cloudify.interfaces.validation:
                creation:
                    implementation: vcloud.network_plugin.public_nat.creation_validation

    cloudify.vcloud.nodes.SecurityGroup:
        derived_from: cloudify.nodes.SecurityGroup
        properties:
            security_group:
                default: {}
            rules:
                default: []
            vcloud_config:
                default: {}
        interfaces:
            cloudify.interfaces.validation:
                creation:
                    implementation: vcloud.network_plugin.security_group.creation_validation

    cloudify.vcloud.nodes.KeyPair:
        derived_from: cloudify.nodes.Root
        properties:
            private_key_path:
                default: ''
            public_key:
                default: {}
            vcloud_config:
                default: {}
        interfaces:
            cloudify.interfaces.validation:
                creation:
                    implementation: vcloud.network_plugin.keypair.creation_validation


    cloudify.vcloud.nodes.Volume:
        derived_from: cloudify.nodes.Volume
        properties:
            volume:
                default: {}
            use_external_resource:
                default: false
            resource_id:
                default: ''
            vcloud_config:
                default: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: vcloud.server_plugin.volume.create_volume
                    inputs: {}
                delete:
                    implementation: vcloud.server_plugin.volume.delete_volume
                    inputs: {}
            cloudify.interfaces.validation:
                creation:
                    implementation: vcloud.server_plugin.volume.creation_validation

relationships:
    cloudify.vcloud.server_connected_to_floating_ip:
        derived_from: cloudify.relationships.connected_to
        target_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                establish:
                    implementation: vcloud.network_plugin.floatingip.connect_floatingip
                    inputs: {}
                unlink:
                    implementation: vcloud.network_plugin.floatingip.disconnect_floatingip
                    inputs: {}
    cloudify.vcloud.server_connected_to_network:
        derived_from: cloudify.relationships.connected_to
    cloudify.vcloud.port_connected_to_network:
        derived_from: cloudify.relationships.connected_to
    cloudify.vcloud.server_connected_to_port:
        derived_from: cloudify.relationships.connected_to
    cloudify.vcloud.server_connected_to_security_group:
        derived_from: cloudify.relationships.connected_to
        target_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                establish:
                    implementation: vcloud.network_plugin.security_group.create
                    inputs: {}
                unlink:
                    implementation: vcloud.network_plugin.security_group.delete
                    inputs: {}
    cloudify.vcloud.net_connected_to_public_nat:
        derived_from: cloudify.relationships.connected_to
        target_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                establish:
                    implementation: vcloud.network_plugin.public_nat.net_connect_to_nat
                    inputs: {}
                unlink:
                    implementation: vcloud.network_plugin.public_nat.net_disconnect_from_nat
                    inputs: {}
    cloudify.vcloud.server_connected_to_public_nat:
        derived_from: cloudify.relationships.connected_to
        target_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                establish:
                    implementation: vcloud.network_plugin.public_nat.server_connect_to_nat
                    inputs: {}
                unlink:
                    implementation: vcloud.network_plugin.public_nat.server_disconnect_from_nat
                    inputs: {}

    cloudify.vcloud.volume_attached_to_server:
        derived_from: cloudify.relationships.connected_to
        target_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                establish:
                    implementation: vcloud.server_plugin.volume.attach_volume
                    inputs: {}
                unlink:
                    implementation: vcloud.server_plugin.volume.detach_volume
                    inputs: {}
